### ISSUE TITLE
Update the package in NuGet?

### ISSUE THREAD

**Issue by nodew** [medo64/PasswordSafe#1]
Hi, nice to see the password core lib clone in C#. I plan to build a cross-platform password-safe application with .NET MAUI. But It seems that the NuGet package hasn't been updated for years https://www.nuget.org/packages/PasswordSafe/ 

Do you have plan to release new package in NuGet?

**Comment by medo64** [comment]
Yes, I do. I am currently updating it for .NET 6 and will probably have a new package in two-three weeks.
I am actually done with expected changes, it's just that I haven't had time to properly test them.

**Comment by nodew** [comment]
Great job!
